//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektovanjePoSlojevimaStudijeApp.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ispit
    {
        public Ispit()
        {
            this.StudentIspits = new HashSet<StudentIspit>();
        }
    
        public int idIspit { get; set; }
        public short idIspitniRok { get; set; }
        public short idPredmet { get; set; }
        public Nullable<System.DateTime> ispitDatum { get; set; }
    
        public virtual IspitniRok IspitniRok { get; set; }
        public virtual Predmet Predmet { get; set; }
        public virtual ICollection<StudentIspit> StudentIspits { get; set; }
    }
}
