//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektovanjePoSlojevimaStudijeApp.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IspitniRok
    {
        public IspitniRok()
        {
            this.Ispits = new HashSet<Ispit>();
        }
    
        public short idIspitniRok { get; set; }
        public short godina { get; set; }
        public string ispitniRokNaziv { get; set; }
        public bool popravni { get; set; }
    
        public virtual ICollection<Ispit> Ispits { get; set; }
    }
}
