//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektovanjePoSlojevimaStudijeApp.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudijeEntities : DbContext
    {
        public StudijeEntities()
            : base("name=StudijeEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ispit> Ispits { get; set; }
        public DbSet<IspitniRok> IspitniRoks { get; set; }
        public DbSet<Predmet> Predmets { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentIspit> StudentIspits { get; set; }
    }
}
